# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- README

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install black
    pip install flake8
    pip install pydocstyle
    flake8 copy2hash/ --count --max-line-length=88 --ignore=W293,W291,W503 --statistics
    black copy2hash/ --check -v
    pydocstyle copy2hash/
  displayName: 'Install dependencies'

- script: |
    python setup.py install
  displayName: 'Install copy2hash'

- script: |
    pip install pytest
    pip install pytest-sugar
    pip install coverage
    pip install pytest-azurepipelines
    coverage run -m pytest
    coverage report -m
    coverage html
    coverage xml
  displayName: 'Test with pytest and coverage'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

- script: pytest --junitxml=junit/test-results.xml

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'
